version: '3'

services:
  my-app:
    image: localhost:5555/my-app:ver1.2
    ports:
     - 3000:3000
    links:
      - mongodb:localhost
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    #networks:
      # frontend-net  # <--- Add this (Network A)
      #- admin-net     # <--- Add this (Network B)

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    #networks:
      #- admin-net     # <--- Add this (Only Network B)

# Define the networks at the root level (bottom of the file)
#networks:
  #frontend-net:
    #driver: bridge
  #admin-net:
    #driver: bridge
